// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subs.sql

package orm

import (
	"context"
)

const getSubCnt = `-- name: GetSubCnt :one
SELECT COUNT(*) FROM subs
WHERE chat = $1
`

func (q *Queries) GetSubCnt(ctx context.Context, chat int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSubCnt, chat)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubsOfChannel = `-- name: GetSubsOfChannel :many
SELECT chat FROM subs
WHERE channel = $1
`

func (q *Queries) GetSubsOfChannel(ctx context.Context, channel int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getSubsOfChannel, channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var chat int64
		if err := rows.Scan(&chat); err != nil {
			return nil, err
		}
		items = append(items, chat)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribe = `-- name: Subscribe :one
INSERT INTO subs(channel, chat)
VALUES ($1, $2)
    RETURNING channel, chat
`

type SubscribeParams struct {
	Channel int64
	Chat    int64
}

func (q *Queries) Subscribe(ctx context.Context, arg SubscribeParams) (Sub, error) {
	row := q.db.QueryRowContext(ctx, subscribe, arg.Channel, arg.Chat)
	var i Sub
	err := row.Scan(&i.Channel, &i.Chat)
	return i, err
}
